language: node_js
node_js:
  - '0.10'
before_script:
  - 'gem update --system'
  - 'gem install sass --version "=3.4.13"'
  - 'gem install compass --version "=1.0.3"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
